packages:
  - packages/*
  - www/*

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@latest

onlyBuiltDependencies:
  - esbuild

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
